export const study = {
  items: [
    {
      id: '71HFE865V215DE1CTEWH0AVNH9',
      title: '연우의 개발공장',
      nickname: 'MK',
      description: '쌓이면 된다',
      backgroundImage: '#FFE4E1',
      totalPoint: 99,
      emojis: [
        { emoji: '🔥', count: 12 },
        { emoji: '👍', count: 7 },
        { emoji: '🌱', count: 3 },
      ],
      createdAt: '2026-01-07T10:00:00.000Z',
    },
    {
      id: '2X7R5JQC42EJ5E6RHXQAQPDH4A',
      title: '알고리즘 루틴',
      nickname: 'AR',
      description: '매일 기록',
      backgroundImage: '#F5F5F5',
      totalPoint: 388,
      emojis: [
        { emoji: '💪', count: 15 },
        { emoji: '🌱', count: 8 },
        { emoji: '✨', count: 4 },
      ],
      createdAt: '2026-01-18T23:10:00.000Z',
    },
    {
      id: 'M3E2MSH4DMDZSX9G8FGVSQE8Z5',
      title: '리액트 매일',
      nickname: 'HN',
      description: '루틴 만들기',
      backgroundImage: 'https://cdn.example.com/bg/bg1.png',
      totalPoint: 432,
      emojis: [
        { emoji: '✨', count: 20 },
        { emoji: '🔥', count: 11 },
        { emoji: '❤️', count: 6 },
      ],
      createdAt: '2026-01-02T03:10:00.000Z',
    },
    {
      id: 'XG07HN7JVAX0GB6KC9QA0MZ17Q',
      title: '백엔드 러닝',
      nickname: 'HN',
      description: '집중하자',
      backgroundImage: '#537ABD',
      totalPoint: 80,
      emojis: [
        { emoji: '👏', count: 5 },
        { emoji: '💪', count: 3 },
      ],
      createdAt: '2026-01-10T07:00:00.000Z',
    },
    {
      id: '88YAGVDCKSQWW7FE4N1EE043E4',
      title: 'CS 기초',
      nickname: '040128',
      description: '오늘도 한 줄',
      backgroundImage: 'https://cdn.example.com/bg/bg3.png',
      totalPoint: 285,
      emojis: [
        { emoji: '🎯', count: 18 },
        { emoji: '💯', count: 9 },
        { emoji: '🧠', count: 5 },
      ],
      createdAt: '2026-01-02T10:00:00.000Z',
    },
    {
      id: '8YFYTC66VPVTX363SN6FCCW8VB',
      title: '타입스크립트 30일',
      nickname: 'SR',
      description: 'Slow and steady...',
      backgroundImage: 'https://cdn.example.com/bg/bg3.png',
      totalPoint: 563,
      emojis: [
        { emoji: '🚀', count: 25 },
        { emoji: '🔥', count: 14 },
        { emoji: '✅', count: 8 },
      ],
      createdAt: '2026-01-09T14:10:00.000Z',
    },
    {
      id: '05FATZYDS3AR0RGXJVZ9CJD33M',
      title: 'DB 설계연구',
      nickname: 'SM',
      description: 'Slow and steady...',
      backgroundImage: 'https://cdn.example.com/bg/bg3.png',
      totalPoint: 543,
      emojis: [
        { emoji: '📊', count: 16 },
        { emoji: '💎', count: 7 },
        { emoji: '🔥', count: 5 },
      ],
      createdAt: '2026-01-02T01:40:00.000Z',
    },
    {
      id: '5B44FS7F25TMGDMFGS8KXM40X6',
      title: '운동 루틴',
      nickname: 'MK',
      description: '매일 1문제',
      backgroundImage: '#F5F5F5',
      totalPoint: 135,
      emojis: [
        { emoji: '💪', count: 22 },
        { emoji: '🔥', count: 10 },
        { emoji: '👏', count: 4 },
      ],
      createdAt: '2026-01-03T17:10:00.000Z',
    },
    {
      id: 'QJAWK0K68G769HJDNDGZG35VH2',
      title: '독서 습관',
      nickname: 'BN23',
      description: '매일 기록',
      backgroundImage: 'https://cdn.example.com/bg/bg1.png',
      totalPoint: 165,
      emojis: [
        { emoji: '📚', count: 19 },
        { emoji: '✨', count: 8 },
        { emoji: '❤️', count: 3 },
      ],
      createdAt: '2026-01-01T10:10:00.000Z',
    },
    {
      id: '07492Q9V82KQ2PDF6PT9FABT1B',
      title: '영어 회화',
      nickname: 'AR',
      description: '꾸준히 하자',
      backgroundImage: '#537ABD',
      totalPoint: 254,
      emojis: [
        { emoji: '🗣️', count: 14 },
        { emoji: '🌍', count: 6 },
        { emoji: '👍', count: 4 },
      ],
      createdAt: '2026-01-11T13:50:00.000Z',
    },
    {
      id: 'R2YECXPKEE1CSNH4HPSN17GBG2',
      title: '프로젝트 집중',
      nickname: 'HJ',
      description: '끝까지',
      backgroundImage: 'https://cdn.example.com/bg/bg3.png',
      totalPoint: 321,
      emojis: [
        { emoji: '🔥', count: 21 },
        { emoji: '💪', count: 12 },
        { emoji: '🚀', count: 7 },
      ],
      createdAt: '2026-01-04T19:30:00.000Z',
    },
    {
      id: '7RCG2V0CQV4NM7KKTMSJ8CTRBK',
      title: '면접 준비',
      nickname: 'HJ',
      description: '끝까지',
      backgroundImage: '#E0F7FA',
      totalPoint: 215,
      emojis: [
        { emoji: '🎤', count: 11 },
        { emoji: '💯', count: 6 },
        { emoji: '✨', count: 4 },
      ],
      createdAt: '2026-01-13T17:00:00.000Z',
    },
    {
      id: 'XWWDYA5JN5FKEC912FY4XTCRZS',
      title: '네트워크 공부',
      nickname: 'HJ',
      description: '오늘도 한 줄',
      backgroundImage: '#FFFFFF',
      totalPoint: 109,
      emojis: [
        { emoji: '🌐', count: 8 },
        { emoji: '📡', count: 4 },
        { emoji: '👍', count: 2 },
      ],
      createdAt: '2026-01-08T04:50:00.000Z',
    },
    {
      id: 'X3F7X8XMWVWAYWGFHZFHW4JFHN',
      title: '운영체제',
      nickname: 'YJ',
      description: '꾸준히 하자',
      backgroundImage: '#F5F5F5',
      totalPoint: 236,
      emojis: [
        { emoji: '⚙️', count: 13 },
        { emoji: '🧠', count: 7 },
        { emoji: '🔥', count: 5 },
      ],
      createdAt: '2026-01-11T17:00:00.000Z',
    },
    {
      id: '4TTNXT3DTR1RY0PKRTEZEHVZ1R',
      title: '코테 스터디',
      nickname: 'BN23',
      description: '꾸준히 하자',
      backgroundImage: 'https://cdn.example.com/bg/bg3.png',
      totalPoint: 169,
      emojis: [
        { emoji: '🧠', count: 17 },
        { emoji: '💪', count: 9 },
        { emoji: '✅', count: 5 },
      ],
      createdAt: '2026-01-11T21:50:00.000Z',
    },
    {
      id: '1S15V8XB3GRMDXMNRHTG5Y13PE',
      title: '디자인 시스템',
      nickname: 'YK',
      description: '오늘도 한 줄',
      backgroundImage: '#EAF2E1',
      totalPoint: 31,
      emojis: [
        { emoji: '🎨', count: 6 },
        { emoji: '✨', count: 3 },
      ],
      createdAt: '2026-01-21T02:50:00.000Z',
    },
    {
      id: '9F8Y7DXGQA7AK61KRSC4F6K72P',
      title: '클린코드',
      nickname: 'JS',
      description: 'Slow and steady...',
      backgroundImage: 'https://cdn.example.com/bg/bg1.png',
      totalPoint: 518,
      emojis: [
        { emoji: '✅', count: 24 },
        { emoji: '🔥', count: 15 },
        { emoji: '💎', count: 8 },
      ],
      createdAt: '2026-01-18T13:50:00.000Z',
    },
    {
      id: 'Z6VQX9VBHYXVHMF5HWFXRN1ZMB',
      title: '테스트 주도',
      nickname: 'AR',
      description: '매일 기록',
      backgroundImage: '#EAF2E1',
      totalPoint: 286,
      emojis: [
        { emoji: '🧪', count: 16 },
        { emoji: '✅', count: 10 },
        { emoji: '🚀', count: 5 },
      ],
      createdAt: '2026-01-16T06:20:00.000Z',
    },
    {
      id: 'C5FTZFYZW15JESFKQYPVNPXHKG',
      title: 'Nest.js 시작',
      nickname: 'SM',
      description: '오늘도 한 줄',
      backgroundImage: '#F5F5F5',
      totalPoint: 122,
      emojis: [
        { emoji: '🐱', count: 9 },
        { emoji: '🔥', count: 5 },
        { emoji: '👍', count: 3 },
      ],
      createdAt: '2026-01-08T03:50:00.000Z',
    },
    {
      id: 'YHJ6CJEQBK08H23J8Z60JYYWNB',
      title: 'Prisma 실습',
      nickname: 'YJ',
      description: '집중하자',
      backgroundImage: '#537ABD',
      totalPoint: 66,
      emojis: [
        { emoji: '💎', count: 7 },
        { emoji: '✨', count: 4 },
      ],
      createdAt: '2026-01-02T08:30:00.000Z',
    },
    {
      id: '399K5F7TERWWKVK36DDG5AFB4A',
      title: 'Next.js 챌린지',
      nickname: 'HB',
      description: 'Slow and steady...',
      backgroundImage: '#F5F5F5',
      totalPoint: 481,
      emojis: [
        { emoji: '⚡', count: 22 },
        { emoji: '🔥', count: 13 },
        { emoji: '🚀', count: 9 },
      ],
      createdAt: '2026-01-01T13:30:00.000Z',
    },
    {
      id: 'JJX4EGCV7E9H943AKJW7XKSHZW',
      title: 'Vue 리마인드',
      nickname: 'AR',
      description: 'Slow and steady...',
      backgroundImage: '#537ABD',
      totalPoint: 330,
      emojis: [
        { emoji: '💚', count: 18 },
        { emoji: '✨', count: 10 },
        { emoji: '👍', count: 6 },
      ],
      createdAt: '2026-01-03T19:00:00.000Z',
    },
    {
      id: 'E1H2BYWHBVZ5YPTNM6ANTZJS2X',
      title: 'Swift 도전',
      nickname: 'J',
      description: '매일 기록',
      backgroundImage: 'https://cdn.example.com/bg/bg2.png',
      totalPoint: 413,
      emojis: [
        { emoji: '🍎', count: 20 },
        { emoji: '🔥', count: 11 },
        { emoji: '💪', count: 7 },
      ],
      createdAt: '2026-01-03T10:20:00.000Z',
    },
    {
      id: 'T3CQZW3DH8JWZ71FAK0T5E7X79',
      title: 'Rust 입문',
      nickname: 'HJ',
      description: '집중하자',
      backgroundImage: 'https://cdn.example.com/bg/bg2.png',
      totalPoint: 279,
      emojis: [
        { emoji: '🦀', count: 14 },
        { emoji: '🔥', count: 8 },
        { emoji: '💪', count: 5 },
      ],
      createdAt: '2026-01-16T22:20:00.000Z',
    },
    {
      id: 'FX9RC84HTNH0JKZ9WYPNRXMCFR',
      title: 'Go 실전',
      nickname: 'YJ',
      description: '루틴 만들기',
      backgroundImage: '#FFFFFF',
      totalPoint: 484,
      emojis: [
        { emoji: '🐹', count: 19 },
        { emoji: '🚀', count: 12 },
        { emoji: '✨', count: 7 },
      ],
      createdAt: '2026-01-08T13:00:00.000Z',
    },
    {
      id: 'Z28N6W6X09T94YGNS5NRMZ24FJ',
      title: 'AWS 기초',
      nickname: 'BN23',
      description: '꾸준히 하자',
      backgroundImage: '#FFE4E1',
      totalPoint: 102,
      emojis: [
        { emoji: '☁️', count: 11 },
        { emoji: '🔥', count: 6 },
        { emoji: '👍', count: 3 },
      ],
      createdAt: '2026-01-08T23:00:00.000Z',
    },
    {
      id: '12M3JPQV9FTBAB5RFZ9EXGXG0X',
      title: 'Docker 매일',
      nickname: 'MK',
      description: '끝까지',
      backgroundImage: '#FFE4E1',
      totalPoint: 452,
      emojis: [
        { emoji: '🐳', count: 23 },
        { emoji: '🔥', count: 14 },
        { emoji: '💪', count: 9 },
      ],
      createdAt: '2026-01-10T21:40:00.000Z',
    },
    {
      id: 'VGXKCRY6FRPJJ1SH03ZJEPECG8',
      title: 'Kotlin 한걸음',
      nickname: 'BN23',
      description: 'Slow and steady...',
      backgroundImage: '#E0F7FA',
      totalPoint: 316,
      emojis: [
        { emoji: '🤖', count: 15 },
        { emoji: '✨', count: 9 },
        { emoji: '🔥', count: 6 },
      ],
      createdAt: '2026-01-21T03:50:00.000Z',
    },
    {
      id: '85JMTBC8QHAGYJN7X49ESQ5S0G',
      title: '자료구조',
      nickname: 'YJ',
      description: '쌓이면 된다',
      backgroundImage: '#537ABD',
      totalPoint: 268,
      emojis: [
        { emoji: '🧠', count: 16 },
        { emoji: '📊', count: 8 },
        { emoji: '💪', count: 5 },
      ],
      createdAt: '2026-01-18T03:30:00.000Z',
    },
    {
      id: 'EY1ME4XKT7822KZ76F8RXQT9T6',
      title: '리눅스 쉘',
      nickname: 'DY',
      description: '집중하자',
      backgroundImage: 'https://cdn.example.com/bg/bg2.png',
      totalPoint: 379,
      emojis: [
        { emoji: '🐧', count: 17 },
        { emoji: '💻', count: 10 },
        { emoji: '🔥', count: 7 },
      ],
      createdAt: '2026-01-16T19:30:00.000Z',
    },
  ],
  pageInfo: {
    pageSize: 6,
    nextCursor: 'EY1ME4XKT7822KZ76F8RXQT9T6',
  },
};
