export const TIME = {
  MINUTES_IN_HOUR: 60,
  SECONDS_IN_MINUTE: 60,
  SECONDS_IN_HOUR: 3600,
  TIMER_INTERVAL: 1000,
};

export const LIMITS = {
  MAX_HOURS: 12,
  MAX_MINUTES: 59,
  RECENT_TIMES_LIMIT: 3,
  INPUT_LIMIT: 2,
};
